-- =====================================================
-- ZielonaApteka — dane startowe
-- Wykonaj w SQL Editor po seed/schema.sql.
-- Bezpieczne do wielokrotnego uruchamiania.
-- =====================================================

-- Migracja kolumn (gdy bazę założono przed tymi polami)
ALTER TABLE herbs ADD COLUMN IF NOT EXISTS appearance_pl    text;
ALTER TABLE herbs ADD COLUMN IF NOT EXISTS where_to_find_pl text;
ALTER TABLE herbs ADD COLUMN IF NOT EXISTS kind             text NOT NULL DEFAULT 'zielo';

-- Migracja: utwórz tabelę food_swaps jeśli jeszcze nie istnieje
CREATE TABLE IF NOT EXISTS food_swaps (
    id                bigserial PRIMARY KEY,
    slug              text NOT NULL UNIQUE,
    unhealthy_name_pl text NOT NULL,
    unhealthy_why_pl  text,
    healthy_name_pl   text NOT NULL,
    healthy_why_pl    text,
    rationale_pl      text,
    icon_unhealthy    text,
    icon_healthy      text,
    sort_order        int NOT NULL DEFAULT 0,
    created_at        timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE food_swaps ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read food_swaps" ON food_swaps;
CREATE POLICY "public read food_swaps" ON food_swaps FOR SELECT USING (true);

-- Kategorie ---------------------------------------------
INSERT INTO categories (slug, name_pl, description, icon, sort_order) VALUES
('bol',       'Ból',                'Leki i zioła stosowane przy bólu głowy, mięśni i stanach zapalnych.', '🤕', 10),
('sen',       'Sen i uspokojenie',  'Wsparcie zdrowego snu, redukcja stresu i napięcia nerwowego.',         '🌙', 20),
('trawienie', 'Trawienie',          'Niestrawność, wzdęcia, biegunka, zgaga i inne dolegliwości żołądka.',  '🌿', 30)
ON CONFLICT (slug) DO NOTHING;

-- Zioła -------------------------------------------------
-- 22 zioła z opisem, sposobem stosowania, ostrzeżeniami, wyglądem i miejscem zakupu.
-- ON CONFLICT (slug) DO UPDATE — bezpieczne wielokrotne uruchamianie, aktualizuje istniejące rekordy.
INSERT INTO herbs (slug, name_pl, latin_name, description_pl, how_to_use_pl, cautions_pl, appearance_pl, where_to_find_pl) VALUES
('wierzba-biala',    'Wierzba biała',     'Salix alba',
 'Kora wierzby zawiera salicynę — naturalny prekursor kwasu salicylowego, działa przeciwbólowo, przeciwgorączkowo i przeciwzapalnie.',
 'Najczęściej w postaci naparu z kory (1 łyżeczka na szklankę wrzątku, 10–15 min) lub gotowych ekstraktów w tabletkach.',
 'Nie stosować przy alergii na salicylany, w ciąży, u dzieci poniżej 12 r.ż. oraz przy chorobach krzepnięcia krwi.',
 'Drzewo do 25 m wysokości, kora szaro-brunatna głęboko popękana, liście długie wąskie srebrzystobiałe od spodu, kwiaty w żółtawych kotkach (bazie).',
 'Apteki — kora w torebkach (Herbapol, Bonimed, Dary Natury) i kapsułki. Drzewo rośnie dziko nad rzekami i jeziorami w całej Polsce.'),
('wiazowka-blotna',  'Wiązówka błotna',   'Filipendula ulmaria',
 'Zawiera salicylany i flawonoidy — działa przeciwzapalnie, przeciwbólowo i przeciwgorączkowo, wspiera stawy.',
 'Napar z kwiatów: 1–2 łyżeczki na szklankę wrzątku, 2–3 razy dziennie.',
 'Przeciwwskazania jak przy wierzbie — alergia na salicylany, astma, ciąża.',
 'Bylina 60–150 cm, kwiaty drobne kremowobiałe w gęstych baldachowatych wiechach o intensywnym słodkim miodowym zapachu, liście pierzaste ząbkowane.',
 'Sklepy zielarskie i apteki (suszone kwiaty Herbapol). Rośnie dziko na podmokłych łąkach i nad rowami w Polsce.'),
('imbir',            'Imbir',             'Zingiber officinale',
 'Działa przeciwzapalnie, przeciwbólowo i przeciwwymiotnie. Pomaga przy bólach mięśni i miesiączkowych.',
 'Świeży korzeń (plasterki) zalany wrzątkiem, gotowe herbaty lub kapsułki.',
 'Ostrożnie przy lekach przeciwzakrzepowych i kamicy żółciowej.',
 'Kłącze brązowe rozgałęzione, soczyste, mięso jasnożółte, charakterystyczny korzenny aromat. Roślina tropikalna do 1 m wysokości, liście wąskie.',
 'Wszędzie — supermarkety i warzywniaki (świeży korzeń), apteki i sklepy ze zdrową żywnością (sproszkowany, kapsułki, herbaty).'),
('melisa-lekarska',  'Melisa lekarska',   'Melissa officinalis',
 'Łagodne działanie uspokajające, nasenne i rozkurczowe. Ułatwia zasypianie i redukuje stres.',
 'Napar z liści: 1–2 łyżeczki na szklankę wrzątku, wieczorem.',
 'Możliwe interakcje z lekami uspokajającymi i przeciwtarczycowymi.',
 'Bylina 30–90 cm, łodyga czworograniasta, liście jajowate karbowane intensywnie cytrynowo pachnące po roztarciu, kwiaty drobne biało-różowe.',
 'Apteki, supermarkety (herbaty Herbapol, Big-Active, Dary Natury), sklepy ogrodnicze. Bardzo łatwa do uprawy w doniczce na parapecie i w ogrodzie.'),
('kozlek-lekarski',  'Kozłek lekarski (waleriana)', 'Valeriana officinalis',
 'Klasyczne zioło na bezsenność i niepokój. Działa wyciszająco bez efektu otępiającego rano.',
 'Napar z korzenia, krople lub tabletki — przyjmować 30–60 min przed snem.',
 'Nie łączyć z alkoholem i benzodiazepinami; ostrożnie przy prowadzeniu pojazdów.',
 'Bylina 50–150 cm, łodyga rurkowata, liście pierzastosieczne, kwiaty drobne jasnoróżowe lub białe w gęstych wiechach. Korzeń o ostrym charakterystycznym zapachu.',
 'Apteki — krople Valdispert/Persen, kapsułki, suszony korzeń (Herbapol). Rośnie dziko w wilgotnych miejscach: nad strumieniami, na łąkach.'),
('chmiel-zwyczajny', 'Chmiel zwyczajny',  'Humulus lupulus',
 'Szyszki chmielu działają uspokajająco i nasennie. Często łączone z walerianą i melisą.',
 'Napar z szyszek lub gotowe preparaty złożone.',
 'Nie zaleca się przy depresji oraz w ciąży.',
 'Pnącze do 6 m, liście dłoniastoklapowe szorstkie, owocostany w postaci jasnozielonych szyszek z aromatycznym żółtym pyłkiem (lupulina).',
 'Sklepy zielarskie i apteki (suszone szyszki Herbapol, Bonimed). Sklepy z piwowarstwem domowym. Rośnie dziko na zaroślach i lasach.'),
('lawenda',          'Lawenda',           'Lavandula angustifolia',
 'Olejek i kwiaty lawendy redukują napięcie, lęk i poprawiają jakość snu.',
 'Napar z kwiatów, olejek do aromaterapii, kapsułki ze standaryzowanym ekstraktem.',
 'Olejek wyłącznie do użytku zewnętrznego lub wziewnego (poza preparatami doustnymi).',
 'Krzewinka do 60 cm, liście wąskie srebrzystoszare, kwiaty drobne fioletowe w długich kłosach, intensywny aromatyczny zapach.',
 'Apteki, drogerie (olejek), sklepy ze zdrową żywnością (suszone kwiaty), sklepy ogrodnicze. Łatwa do uprawy w słonecznym ogrodzie.'),
('czarna-jagoda',    'Czarna jagoda (borówka czernica)', 'Vaccinium myrtillus',
 'Suszone owoce mają działanie ściągające i przeciwbiegunkowe dzięki garbnikom.',
 'Odwar z suszonych owoców (1 łyżka na szklankę, gotować 10 min), 2–3 razy dziennie.',
 'Nie stosować dłużej niż kilka dni; uwaga na zaparcia przy przedawkowaniu.',
 'Krzewinka 15–50 cm, liście drobne owalne ciemnozielone, owoce niebiesko-czarne kuleczki 5–8 mm z intensywnym fioletowym sokiem.',
 'Apteki (suszone owoce Herbapol), sklepy zielarskie. Świeże w sezonie (lipiec–sierpień) na bazarach i w sklepach. Rośnie dziko w lasach iglastych w Polsce.'),
('pieciornik',       'Pięciornik kurze ziele', 'Potentilla erecta',
 'Bogaty w garbniki — działa silnie ściągająco, przeciwbiegunkowo i przeciwzapalnie na śluzówki.',
 'Odwar z kłącza: 1 łyżeczka na szklankę, gotować 5 min.',
 'Krótkotrwale; przy wrażliwym żołądku może powodować mdłości.',
 'Bylina 10–30 cm, kłącze grube brunatnoczerwone (po przekrojeniu krwistoczerwone), liście trójkrotne, kwiaty drobne żółte czterokrotne (rzadkość wśród potencyl).',
 'Sklepy zielarskie i apteki (suszone kłącze, Herbapol). Rośnie dziko na łąkach, wrzosowiskach i w widnych lasach w Polsce.'),
('koper-wloski',     'Koper włoski',      'Foeniculum vulgare',
 'Owoce kopru działają wiatropędnie i rozkurczowo — łagodzą wzdęcia i kolki.',
 'Napar z rozgniecionych owoców: 1 łyżeczka na szklankę wrzątku, po posiłkach.',
 'Generalnie bezpieczny; ostrożnie przy alergii na rośliny baldaszkowate.',
 'Bylina 1–2 m, liście pierzastosieczne nitkowate (jak koper ogrodowy), kwiaty żółte w baldachach, owoce podłużne brunatne, aromat anyżkowy.',
 'Apteki (Herbapol, Bonimed) — owoce mielone i całe. Sklepy spożywcze (przyprawa). Łatwa do uprawy w ogrodzie.'),
('mieta-pieprzowa',  'Mięta pieprzowa',   'Mentha × piperita',
 'Olejek mentolowy działa rozkurczowo na mięśnie gładkie przewodu pokarmowego.',
 'Napar z liści po posiłkach lub kapsułki dojelitowe z olejkiem (IBS).',
 'Nasila refluks żołądkowo-przełykowy; nie stosować u niemowląt.',
 'Bylina 30–90 cm, łodyga czworograniasta czerwonawa, liście jajowate karbowane, kwiaty drobne fioletowe w kłosach. Intensywny zapach mentolu.',
 'Wszędzie — apteki (Herbapol, Mentol), supermarkety (herbaty), warzywniaki (świeża). Bardzo łatwa do uprawy w doniczce.'),
('rumianek',         'Rumianek',          'Matricaria chamomilla',
 'Działa przeciwzapalnie, rozkurczowo i wiatropędnie. Łagodzi podrażnienia żołądka.',
 'Napar z koszyczków kwiatowych: 1 łyżka na szklankę wrzątku.',
 'Rzadkie alergie krzyżowe (ambrozja).',
 'Roślina jednoroczna 20–50 cm, liście pierzastosieczne nitkowate, kwiatostany koszyczki z białymi kwiatami brzeżnymi i wypukłym żółtym środkiem, charakterystyczny aromat.',
 'Wszędzie — apteki, sklepy spożywcze (herbaty), drogerie. Często rośnie dziko jako chwast na poboczach dróg, ugorach i polach.'),
('lukrecja',         'Lukrecja',          'Glycyrrhiza glabra',
 'Korzeń lukrecji wspomaga regenerację błony śluzowej żołądka, łagodzi zgagę.',
 'Odwar z korzenia lub gotowe ekstrakty DGL (deglicyrrhized).',
 'Długotrwałe stosowanie podnosi ciśnienie krwi i obniża potas. Nie w nadciśnieniu i ciąży.',
 'Bylina 1–1,5 m, korzeń długi pomarszczony żółtawy w środku, liście pierzaste, kwiaty drobne fioletowe w gronach.',
 'Apteki (cukierki, ekstrakty DGL: Bonimed, Solgar), sklepy zielarskie i ze zdrową żywnością. Sklepy z przyprawami (jako słodzik).'),
('siemie-lniane',    'Siemię lniane',     'Linum usitatissimum',
 'Śluzy roślinne pokrywają śluzówkę żołądka i przełyku — łagodzą zgagę i podrażnienia.',
 'Macerat: 1 łyżka nasion zalana letnią wodą na 20–30 min, pić ze śluzem.',
 'Świeżo zmielone siemię — krótkotrwałe przechowywanie.',
 'Roślina jednoroczna 30–100 cm, liście wąskie zielone, kwiaty błękitne pięciopłatkowe, nasiona owalne brązowe lub złociste, gładkie.',
 'Wszędzie — apteki, sklepy spożywcze (siemię, mąka lniana), zdrowa żywność. Bardzo tanie. Pole lnu czasem widać na wsi.'),
('prawoslaz',        'Prawoślaz lekarski','Althaea officinalis',
 'Korzeń prawoślazu zawiera śluzy łagodzące podrażnienia gardła, przełyku i żołądka.',
 'Macerat na zimno z korzenia (1 łyżka na szklankę, 1–2 godz.).',
 'Może opóźniać wchłanianie innych leków — odstęp 1–2 godz.',
 'Bylina do 2 m, liście dłoniastoklapowe pokryte gęstymi miękkimi włoskami (aksamitne w dotyku), kwiaty bladoróżowe pięciopłatkowe.',
 'Apteki i sklepy zielarskie (suszony korzeń i kwiaty Herbapol, Bonimed). Rośnie dziko na nadbrzeżach rzek, słonych łąkach.'),
('harpagofyt',       'Czarci pazur (harpagofyt)', 'Harpagophytum procumbens',
 'Korzeń pochodzący z Afryki o silnym działaniu przeciwbólowym i przeciwzapalnym, szczególnie w bólach stawów i kręgosłupa.',
 'Standaryzowane kapsułki 400–600 mg dziennie; napar z korzenia gorzki.',
 'Choroba wrzodowa, kamica żółciowa, ciąża; może obniżać poziom cukru.',
 'Pełzająca roślina afrykańska, owoce mają charakterystyczne zaczepione drewniane kolce (stąd "czarci pazur"), kwiaty czerwono-fioletowe lejkowate, korzeń tworzy duże bulwy.',
 'Apteki i sklepy ze zdrową żywnością — wyłącznie kapsułki/tabletki ze standaryzowanym ekstraktem (Doppelherz, Olimp, Herbapol). Nie rośnie w Polsce.'),
('dziurawiec',       'Dziurawiec zwyczajny', 'Hypericum perforatum',
 'Tradycyjnie stosowany przy łagodnych stanach depresyjnych, niepokoju i bezsenności.',
 'Napar z ziela: 1 łyżeczka na szklankę, 2 razy dziennie.',
 'Bardzo dużo interakcji lekowych (leki antykoncepcyjne, przeciwzakrzepowe, antydepresanty)! Fotouczulający.',
 'Bylina 30–80 cm, łodyga z dwiema wzdłużnymi listewkami, liście drobne z jasnymi punktami przeświecającymi pod światło (gruczoły olejkowe), kwiaty żółte pięciopłatkowe. Po roztarciu między palcami olej barwi je krwistoczerwono.',
 'Apteki (suszone ziele Herbapol, Bonimed), sklepy zielarskie, oleje (Hyperici Oil) w aptekach. Bardzo pospolity dziko na słonecznych miedzach, przydrożach, ugorach.'),
('owies',            'Owies zwyczajny', 'Avena sativa',
 'Niedojrzałe ziarno owsa działa odżywczo na układ nerwowy, łagodzi napięcie i wspomaga sen.',
 'Owsianka, napar ze słomy owsianej, gotowe nalewki.',
 'Bezpieczny; uwaga przy celiakii (zanieczyszczenia glutenem).',
 'Trawa zbożowa 60–120 cm, kłosy w postaci luźnej rozłożystej wiechy z luźno zwisającymi kłoskami, ziarna osłonięte plewami.',
 'Sklepy spożywcze i ze zdrową żywnością (płatki, otręby, mąka — Sante, Bio Planet). Słoma owsiana w aptekach i sklepach zielarskich. Pola owsa pospolite na wsi.'),
('senes',            'Senes (strączyniec)', 'Senna alexandrina',
 'Liście i strąki działają silnie przeczyszczająco poprzez pobudzenie perystaltyki jelita grubego.',
 'Napar lub gotowe tabletki, krótkotrwale (do 1–2 tygodni).',
 'Nie przewlekle (przyzwyczajenie jelit), nie w ciąży i u dzieci, kolki, biegunka.',
 'Krzew tropikalny 1–2 m, liście pierzaste z 4–7 par podłużnych listków, kwiaty żółte pięciopłatkowe, strąki płaskie brązowe zawierające 6–7 nasion.',
 'Apteki — suszone liście (Senesi folium) lub strąki, gotowe preparaty (Senalax, Xenna, Alax). Importowany; nie rośnie w Polsce.'),
('babka-jajowata',   'Babka jajowata (psyllium)', 'Plantago ovata',
 'Łuski nasion (psyllium) tworzą żel wodny — błonnik regulujący wypróżnienia, działa zarówno przy zaparciach jak i biegunkach.',
 'Łyżeczka łusek wymieszana z dużą szklanką wody, dziennie.',
 'Pij dużo wody; może opóźniać wchłanianie leków — odstęp 2 godz.',
 'Roślina jednoroczna 10–50 cm, liście wąskie lancetowate, kłosy z drobnymi kwiatkami, nasiona drobne brunatne otoczone białą łuską (ta łuska to psyllium husk).',
 'Apteki i sklepy ze zdrową żywnością — łuski/Husk Psyllium (Olimp, Now Foods, Holland & Barrett, Bonimed). Importowana z Indii i Iranu.'),
('ostropest',        'Ostropest plamisty', 'Silybum marianum',
 'Sylimaryna chroni komórki wątroby i wspiera ich regenerację.',
 'Mielone nasiona (1 łyżka dziennie) lub kapsułki ze standaryzowanym ekstraktem.',
 'Ogólnie bezpieczny; możliwa alergia u osób uczulonych na rośliny astrowate.',
 'Roślina dwuletnia 1–1,5 m, łodyga pojedyncza, liście duże z kolczastymi brzegami i charakterystycznym białym żyłkowaniem (jakby mleko rozlane na liściu), kwiaty fioletoworóżowe w dużych koszyczkach z kolcami.',
 'Apteki i sklepy zielarskie — mielone nasiona (Bonimed, Olimp, Doppelherz, Sylimarol) i kapsułki sylimaryny. Czasem rośnie dziko jako uciążliwy chwast.'),
('karczoch',         'Karczoch zwyczajny', 'Cynara scolymus',
 'Liście karczocha pobudzają wydzielanie żółci i wspierają trawienie tłuszczów.',
 'Kapsułki z ekstraktem lub napar z liści.',
 'Niedrożność dróg żółciowych, kamica; alergie na astrowate.',
 'Roślina 1–2 m, liście duże pierzastosieczne srebrzystoszare, kwiatostany w postaci dużych zielono-fioletowych koszyczków (jadalne pąki), kwiaty fioletowe wewnątrz koszyczka.',
 'Apteki — kapsułki z ekstraktem liści (Cynacholin, Hepatil, Raphacholin). Świeże główki w supermarketach jako warzywo (głównie jesień).'),
('mniszek',          'Mniszek lekarski', 'Taraxacum officinale',
 'Korzeń wspiera wątrobę i nerki, działa moczopędnie.',
 'Napar z korzenia lub liści, kawa z korzenia mniszka.',
 'Niedrożność dróg żółciowych, ostre stany żołądka.',
 'Bylina 10–40 cm, korzeń palowy długi z białym mleczkiem, rozeta liści pierzastoząbkowanych przy ziemi, kwiaty żółte koszyczki na bezlistnej łodydze, później "dmuchawce" z lotnymi nasionami.',
 'Wszędzie — apteki (suszony korzeń, kawa z mniszka Inka, Pini Mors), sklepy zielarskie. Pospolicie rośnie dziko w trawnikach, na łąkach, polach — jeden z najczęstszych chwastów.')
ON CONFLICT (slug) DO UPDATE SET
  name_pl          = EXCLUDED.name_pl,
  latin_name       = EXCLUDED.latin_name,
  description_pl   = EXCLUDED.description_pl,
  how_to_use_pl    = EXCLUDED.how_to_use_pl,
  cautions_pl      = EXCLUDED.cautions_pl,
  appearance_pl    = EXCLUDED.appearance_pl,
  where_to_find_pl = EXCLUDED.where_to_find_pl;

-- Owoce i warzywa --------------------------------------
-- Naturalne pokarmy o działaniu zbliżonym do leków.
INSERT INTO herbs (slug, name_pl, latin_name, description_pl, how_to_use_pl, cautions_pl, appearance_pl, where_to_find_pl, kind) VALUES
('wisnie-cierpkie',  'Wiśnie cierpkie (Montmorency)', 'Prunus cerasus',
 'Naturalne źródło melatoniny i antocyjanów — wspierają sen i działają przeciwzapalnie. Badania potwierdzają lepszy sen u osób spożywających sok z wiśni cierpkich.',
 'Sok z wiśni cierpkich (240 ml) lub suszone wiśnie 2x dziennie, ostatnia porcja 1–2 godz. przed snem.',
 'Wysoka zawartość fruktozy — uważać przy cukrzycy i IBS.',
 'Drzewo do 6 m, owoce kuliste ciemnoczerwone, kwaśne w smaku, miąższ jasnoczerwony, pestka twarda.',
 'Sklepy ze zdrową żywnością i apteki (sok z wiśni cierpkich Montmorency: Solgar, Now Foods, Ekamedica). Świeże w sezonie (lipiec) na bazarach.',
 'owoc'),
('ananas',           'Ananas',                 'Ananas comosus',
 'Bromelina — enzym proteolityczny o silnym działaniu przeciwzapalnym i przeciwobrzękowym, wspiera trawienie białek.',
 'Świeży ananas (1 plaster po posiłku) lub kapsułki z bromeliną 500 mg.',
 'Może nasilać działanie leków przeciwzakrzepowych; uczulenia.',
 'Owoc tropikalny, zewnątrz brunatno-zielony łuskowaty, w środku miąższ żółty soczysty, korona zielonych liści.',
 'Supermarkety (świeży i puszkowany), apteki (kapsułki bromeliny: Olimp, Now Foods, Solgar).',
 'owoc'),
('banan',            'Banan',                  'Musa × paradisiaca',
 'Bogaty w potas i magnez wspiera układ nerwowy. Niedojrzałe banany zawierają skrobię oporną — łagodzą biegunkę (część diety BRAT).',
 'Lekko niedojrzały banan przy biegunce; dojrzały jako codzienny posiłek dla potasu i magnezu.',
 'Wysoka zawartość cukru przy cukrzycy.',
 'Owoc tropikalny zakrzywiony, skórka żółta po dojrzeniu (zielona przed), miąższ kremowy.',
 'Wszędzie — supermarkety, warzywniaki, sklepy spożywcze. Bardzo tanie i powszechne.',
 'owoc'),
('jablko',           'Jabłko',                 'Malus domestica',
 'Pektyny działają regulująco na jelita — przy biegunce wiążą wodę, przy zaparciach łagodzą poprzez błonnik. "Jeden jabłko dziennie..."',
 'Tarte jabłko (z brunatnieniem) przy biegunce; surowe jabłko ze skórką przy zaparciach.',
 'Skórka może powodować wzdęcia u osób wrażliwych.',
 'Owoc kulisty 5–10 cm, skórka czerwona/zielona/żółta, miąższ jasny, nasiona w środku.',
 'Wszędzie — sklepy, sady, ogrody. Polska jest w światowej czołówce produkcji.',
 'owoc'),
('suszone-sliwki',   'Suszone śliwki',         'Prunus domestica',
 'Naturalny środek przeczyszczający — błonnik i sorbitol pobudzają perystaltykę. Skuteczne przy zaparciach.',
 '5–10 sztuk dziennie, najlepiej namoczonych przez noc.',
 'Wysokokaloryczne, dużo cukrów; ostrożnie przy cukrzycy.',
 'Suszone owoce ciemnobrązowe pomarszczone, słodkie, z pestką lub bez.',
 'Sklepy spożywcze i ze zdrową żywnością — Sante, Bakalland, Helio. Bazary (od polskich producentów).',
 'owoc'),
('marchew',          'Marchew',                'Daucus carota',
 'Gotowana marchew (zupa marchwiowa) jest klasycznym domowym sposobem na biegunkę u dzieci i dorosłych — pektyny wiążą wodę.',
 'Zupa marchwiowa (gotowana z marchwi z odrobiną soli, miksowana) 3x dziennie przy biegunce; surowa codziennie dla wzroku.',
 'Bezpieczna; nadmierne spożycie powoduje karotenodermię (żółta skóra, odwracalne).',
 'Korzeń pomarańczowy stożkowaty 15–25 cm, liście pierzaste zielone u góry.',
 'Wszędzie — warzywniaki, supermarkety, sklepy. Łatwa do uprawy w ogrodzie.',
 'warzywo'),
('buraki',           'Buraki czerwone',        'Beta vulgaris',
 'Bogate w błonnik (na zaparcia) i azotany (obniżające ciśnienie krwi). Betalainy wspierają wątrobę.',
 'Gotowane lub pieczone buraki, sok z buraka, kwas chlebowy z buraków.',
 'Mogą barwić mocz i stolec na czerwono (bezpieczne); wysokie szczawiany przy kamicy.',
 'Korzeń kulisty czerwony lub bordowy 5–10 cm, liście duże ciemnozielone z czerwonymi żyłkami.',
 'Wszędzie — warzywniaki, sklepy. Polska tradycyjnie spożywa.',
 'warzywo'),
('brokuly',          'Brokuły',                'Brassica oleracea italica',
 'Sulforafan — potężny antyoksydant wspierający detoksykację wątroby i ochronę komórek. Witamina C i K.',
 'Lekko gotowane na parze (3–5 min) zachowują najwięcej sulforafanu. Surowe w sałatkach.',
 'Goitrogeny — przy chorobach tarczycy ostrożnie z dużymi ilościami surowych.',
 'Roślina kapustna z dużym kwiatostanem zielono-fioletowym przypominającym drzewko, łodyga jadalna gruba.',
 'Wszędzie — supermarkety, warzywniaki, sklepy ze zdrową żywnością.',
 'warzywo'),
('kapusta-kiszona',  'Kapusta kiszona',        'Brassica oleracea',
 'Naturalne probiotyki (bakterie kwasu mlekowego), witamina C, błonnik — wspierają mikrobiom jelitowy i trawienie.',
 '50–100 g kiszonki dziennie do posiłków, sok z kiszonej kapusty na czczo.',
 'Wysoka zawartość soli; ostrożnie przy nadciśnieniu.',
 'Włókna i liście kapusty kiszone w słonej zalewie, bladożółte, kwaśne, charakterystyczny zapach fermentacji.',
 'Sklepy spożywcze (kiszonki: Polski Ogród, Nasze Kiszonki), bazary (z beczki), kiszenie domowe.',
 'warzywo'),
('czosnek',          'Czosnek',                'Allium sativum',
 'Allicyna — naturalny antybiotyk i przeciwzapalny. Wspiera odporność, obniża ciśnienie i cholesterol.',
 '1–2 ząbki dziennie surowe (rozgniecione 10 min przed spożyciem aktywują allicynę).',
 'Może nasilać działanie leków przeciwzakrzepowych; refluks; nieprzyjemny zapach z ust.',
 'Cebulopodobna roślina z białymi/fioletowymi główkami złożonymi z ząbków, łodygi rurkowate zielone.',
 'Wszędzie — supermarkety, warzywniaki, sklepy ze zdrową żywnością (kapsułki ekstraktu czosnku: Olimp, Now Foods).',
 'warzywo')
ON CONFLICT (slug) DO UPDATE SET
  name_pl          = EXCLUDED.name_pl,
  latin_name       = EXCLUDED.latin_name,
  description_pl   = EXCLUDED.description_pl,
  how_to_use_pl    = EXCLUDED.how_to_use_pl,
  cautions_pl      = EXCLUDED.cautions_pl,
  appearance_pl    = EXCLUDED.appearance_pl,
  where_to_find_pl = EXCLUDED.where_to_find_pl,
  kind             = EXCLUDED.kind;

-- Leki --------------------------------------------------
INSERT INTO medications (slug, name_pl, active_substance, brand_examples, purpose_pl, description_pl, side_effects_pl, category_id)
SELECT * FROM (VALUES
('ibuprofen',    'Ibuprofen',    'Ibuprofen',                'Ibuprom, Nurofen, MIG',
 'Ból, gorączka, stany zapalne',
 'Niesteroidowy lek przeciwzapalny (NLPZ) o działaniu przeciwbólowym, przeciwzapalnym i przeciwgorączkowym. Stosowany w bólu głowy, mięśni, miesiączkowym i przy infekcjach.',
 'Podrażnienie żołądka, nudności, ryzyko krwawień z przewodu pokarmowego, wzrost ciśnienia.',
 (SELECT id FROM categories WHERE slug='bol')),
('paracetamol',  'Paracetamol',  'Paracetamol',              'Apap, Panadol, Codipar',
 'Ból, gorączka',
 'Łagodny lek przeciwbólowy i przeciwgorączkowy. Nie ma działania przeciwzapalnego, ale jest dobrze tolerowany przez żołądek.',
 'Przy przedawkowaniu — toksyczne uszkodzenie wątroby. Ostrożnie z alkoholem.',
 (SELECT id FROM categories WHERE slug='bol')),
('aspiryna',     'Aspiryna',     'Kwas acetylosalicylowy',   'Polopiryna, Aspirin',
 'Ból, gorączka, profilaktyka sercowo-naczyniowa',
 'Klasyczny NLPZ. W małych dawkach stosowany jako lek przeciwzakrzepowy. W większych — przeciwbólowo i przeciwzapalnie.',
 'Krwawienia z przewodu pokarmowego, alergie, zespół Reye u dzieci.',
 (SELECT id FROM categories WHERE slug='bol')),
('melatonina',   'Melatonina',   'Melatonina',               'Melatonina LEK-AM, Circadin',
 'Trudności z zasypianiem, jet lag',
 'Hormon wytwarzany przez szyszynkę regulujący rytm dobowy. Stosowany przy bezsenności i zmianach stref czasowych.',
 'Senność rano, bóle głowy, żywe sny. Może wchodzić w interakcje z lekami przeciwzakrzepowymi.',
 (SELECT id FROM categories WHERE slug='sen')),
('hydroksyzyna', 'Hydroksyzyna', 'Hydroksyzyna',             'Atarax, Hydroxyzinum VP',
 'Lęk, niepokój, bezsenność',
 'Lek przeciwhistaminowy o działaniu uspokajającym i przeciwlękowym. Wymaga recepty.',
 'Senność, suchość w ustach, zaburzenia rytmu serca (długie QT). Nie łączyć z alkoholem.',
 (SELECT id FROM categories WHERE slug='sen')),
('loperamid',    'Loperamid',    'Loperamid',                'Stoperan, Imodium, Laremid',
 'Biegunka',
 'Hamuje perystaltykę jelit, wskazany w ostrej, niezakaźnej biegunce u dorosłych.',
 'Zaparcia, bóle brzucha. Niewskazany w biegunce z gorączką lub krwią w stolcu.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('espumisan',    'Espumisan',    'Symetykon',                'Espumisan, Esputicon',
 'Wzdęcia, gazy',
 'Środek przeciwpieniący — rozbija pęcherzyki gazu w jelitach. Nie wchłania się do krwiobiegu.',
 'Praktycznie brak; rzadko reakcje alergiczne.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('omeprazol',    'Omeprazol',    'Omeprazol',                'Polprazol, Helicid, Bioprazol',
 'Zgaga, refluks, choroba wrzodowa',
 'Inhibitor pompy protonowej — zmniejsza wydzielanie kwasu solnego w żołądku.',
 'Bóle głowy, biegunka, długotrwale — niedobór B12 i magnezu, ryzyko złamań.',
 (SELECT id FROM categories WHERE slug='trawienie')),
-- Nowe leki ----------------------------------------------
('ketoprofen',   'Ketoprofen',   'Ketoprofen',               'Ketonal, Bi-Profenid, Profenid',
 'Ból, stany zapalne stawów',
 'Niesteroidowy lek przeciwzapalny (NLPZ) — silnie przeciwbólowy i przeciwzapalny, używany w bólach stawów, mięśni i pooperacyjnych.',
 'Podrażnienie żołądka, owrzodzenia, problemy nerkowe, fotoalergia (żel).',
 (SELECT id FROM categories WHERE slug='bol')),
('diclofenac',   'Diclofenac',   'Diklofenak',               'Voltaren, Olfen, Naklofen, Dicloratio',
 'Ból, zapalenie stawów',
 'NLPZ stosowany w bólu kostno-stawowym, urazach, dnie moczanowej. Dostępny doustnie i miejscowo (żel).',
 'Powikłania sercowo-naczyniowe przy długim stosowaniu, podrażnienie żołądka.',
 (SELECT id FROM categories WHERE slug='bol')),
('naproksen',    'Naproksen',    'Naproksen',                'Naproxen, Aleve, Naprosyn',
 'Ból, gorączka, zapalenie',
 'NLPZ o długim działaniu (do 12 godzin). Często stosowany w bólach miesiączkowych i głowy.',
 'Podrażnienie żołądka, retencja płynów, ostrożnie u osób z chorobami serca.',
 (SELECT id FROM categories WHERE slug='bol')),
('drotaweryna',  'No-Spa',       'Drotaweryna',              'No-Spa, Galospa, Drotaverin',
 'Bóle skurczowe (kolka, miesiączkowy)',
 'Lek rozkurczowy działający na mięśnie gładkie — kolka jelitowa, żółciowa, nerkowa, ból miesiączkowy.',
 'Spadki ciśnienia, zawroty głowy. Nie u dzieci poniżej 1 r.ż.',
 (SELECT id FROM categories WHERE slug='bol')),
('doksylamina',  'Doksylamina',  'Doksylamina',              'Noctis, Donormyl',
 'Krótkotrwała bezsenność',
 'Lek przeciwhistaminowy I generacji o silnym działaniu nasennym. Bez recepty.',
 'Senność rano, suchość w ustach, zaparcia. Tolerancja przy częstym użyciu.',
 (SELECT id FROM categories WHERE slug='sen')),
('magne-b6',     'Magne B6',     'Magnez + witamina B6',     'Magne B6, Magnefar B6, Slow Mag',
 'Niedobór magnezu, napięcie nerwowe, sen',
 'Suplementacja magnezu z B6 wspiera układ nerwowy, łagodzi skurcze i ułatwia zasypianie.',
 'Biegunka przy dużych dawkach, ostrożnie przy chorobach nerek.',
 (SELECT id FROM categories WHERE slug='sen')),
('zolpidem',     'Stilnox (Zolpidem)', 'Zolpidem',           'Stilnox, Hypnogen, Nasen',
 'Ciężka bezsenność (na receptę)',
 'Niebenzodiazepinowy lek nasenny o szybkim działaniu. Stosowany krótkotrwale (do 4 tygodni).',
 'Uzależnienie, ataksja, halucynacje, lunatykowanie. Nie z alkoholem.',
 (SELECT id FROM categories WHERE slug='sen')),
('ranitydyna',   'Ranigast',     'Ranitydyna / Famotydyna',  'Ranigast, Pepcid, Famogast',
 'Zgaga, nadkwaśność',
 'Bloker receptora H2 — zmniejsza wydzielanie kwasu żołądkowego, łagodniejszy od IPP.',
 'Bóle głowy, biegunka. Ranitydyna wycofana w wielu krajach (zanieczyszczenia NDMA).',
 (SELECT id FROM categories WHERE slug='trawienie')),
('smecta',       'Smecta',       'Diosmektyt',               'Smecta, Smectago',
 'Ostra biegunka',
 'Krzemian glinu o właściwościach absorpcyjnych — wiąże toksyny i drobnoustroje, łagodzi biegunkę.',
 'Zaparcia. Może opóźniać wchłanianie innych leków — odstęp 2 godz.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('bisakodyl',    'Dulcolax (Bisakodyl)', 'Bisakodyl',        'Dulcolax, Bisacodyl',
 'Zaparcia',
 'Stymulujący środek przeczyszczający — pobudza perystaltykę jelita grubego po 6–12 godzinach.',
 'Skurcze brzucha, biegunka, utrata elektrolitów. Nie do długotrwałego użycia.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('forlax',       'Forlax (Makrogol)', 'Makrogol 4000',       'Forlax, Movicol, Fortrans',
 'Zaparcia',
 'Osmotyczny środek przeczyszczający — wiąże wodę w jelicie. Łagodny, nadaje się do długiego stosowania.',
 'Wzdęcia, lekkie odwodnienie. Bezpieczny u dzieci i kobiet w ciąży.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('hepatil',      'Hepatil',      'Asparaginian L-ornityny',  'Hepatil, Hepatil Trawienie',
 'Wsparcie wątroby',
 'Aminokwas wspomagający detoksykację amoniaku w wątrobie. Stosowany przy stanach zapalnych i niewydolności.',
 'Generalnie bezpieczny; ostrożnie przy ciężkiej niewydolności nerek.',
 (SELECT id FROM categories WHERE slug='trawienie'))
) AS v(slug, name_pl, active_substance, brand_examples, purpose_pl, description_pl, side_effects_pl, category_id)
ON CONFLICT (slug) DO NOTHING;

-- Powiązania lek <-> zioło ------------------------------
INSERT INTO medication_herbs (medication_id, herb_id, rationale_pl, strength)
SELECT m.id, h.id, r.rationale, r.strength
FROM (VALUES
('ibuprofen',    'wierzba-biala',    'Naturalny salicylan o działaniu przeciwbólowym i przeciwzapalnym — botaniczny pierwowzór aspiryny.', 4),
('ibuprofen',    'wiazowka-blotna',  'Bogata w salicylany — wspiera stawy i działa przeciwzapalnie.', 3),
('paracetamol',  'wierzba-biala',    'Łagodny efekt przeciwbólowy i przeciwgorączkowy.', 3),
('paracetamol',  'imbir',            'Działa przeciwbólowo i przeciwzapalnie, szczególnie w bólach mięśni i miesiączkowych.', 3),
('aspiryna',     'wierzba-biala',    'Bezpośredni botaniczny odpowiednik — kora wierzby była pierwowzorem aspiryny.', 5),
('aspiryna',     'wiazowka-blotna',  'Druga klasyczna roślina salicylanowa.', 4),
('melatonina',   'melisa-lekarska',  'Łagodzi zasypianie i redukuje napięcie wieczorem.', 3),
('melatonina',   'kozlek-lekarski',  'Skraca czas zasypiania i poprawia jakość snu.', 4),
('hydroksyzyna', 'melisa-lekarska',  'Działa przeciwlękowo i uspokajająco.', 3),
('hydroksyzyna', 'chmiel-zwyczajny', 'Wzmacnia działanie waleriany i melisy.', 3),
('hydroksyzyna', 'lawenda',          'Redukuje lęk, poprawia jakość snu.', 4),
('loperamid',    'czarna-jagoda',    'Garbniki działają ściągająco i przeciwbiegunkowo.', 4),
('loperamid',    'pieciornik',       'Silne działanie ściągające na śluzówkę jelit.', 4),
('espumisan',    'koper-wloski',     'Wiatropędnie usuwa nadmiar gazów i łagodzi kolki.', 4),
('espumisan',    'mieta-pieprzowa',  'Rozkurcza mięśnie gładkie jelit.', 4),
('espumisan',    'rumianek',         'Łagodzi podrażnienia i wspiera trawienie.', 3),
('omeprazol',    'lukrecja',         'Wspiera regenerację błony śluzowej żołądka — szczególnie postać DGL.', 4),
('omeprazol',    'siemie-lniane',    'Śluzy chronią przełyk i żołądek przed kwasem.', 3),
('omeprazol',    'prawoslaz',        'Tworzy ochronną warstwę śluzu na śluzówce.', 3),
-- Nowe leki -> zioła ------------------------------------
('ketoprofen',   'wierzba-biala',    'Salicylany działają przeciwzapalnie i przeciwbólowo.', 4),
('ketoprofen',   'harpagofyt',       'Czarci pazur — silne wsparcie przy bólach stawów i kręgosłupa.', 5),
('ketoprofen',   'imbir',            'Działa przeciwzapalnie i przeciwbólowo na stawy.', 3),
('diclofenac',   'wierzba-biala',    'Naturalny salicylan o działaniu przeciwzapalnym.', 4),
('diclofenac',   'harpagofyt',       'Tradycyjne wsparcie przy zapaleniach stawów.', 4),
('diclofenac',   'wiazowka-blotna',  'Salicylany roślinne łagodzące stany zapalne.', 3),
('naproksen',    'wierzba-biala',    'Klasyczny botaniczny prekursor NLPZ.', 4),
('naproksen',    'wiazowka-blotna',  'Wspiera leczenie bólów reumatycznych.', 3),
('drotaweryna',  'mieta-pieprzowa',  'Olejek mentolowy rozkurcza mięśnie gładkie jelit.', 4),
('drotaweryna',  'koper-wloski',     'Działa rozkurczowo i wiatropędnie.', 3),
('drotaweryna',  'melisa-lekarska',  'Łagodne działanie rozkurczowe i uspokajające.', 3),
('doksylamina',  'kozlek-lekarski',  'Tradycyjne zioło na sen.', 4),
('doksylamina',  'melisa-lekarska',  'Łagodzi zasypianie.', 3),
('doksylamina',  'chmiel-zwyczajny', 'Działa nasennie, wzmacnia walerianę.', 3),
('magne-b6',     'owies',            'Niedojrzałe ziarno owsa odżywia układ nerwowy.', 3),
('magne-b6',     'melisa-lekarska',  'Łagodzi napięcie nerwowe.', 3),
('zolpidem',     'kozlek-lekarski',  'Najsilniejsze tradycyjne zioło na bezsenność.', 4),
('zolpidem',     'chmiel-zwyczajny', 'Wzmacnia działanie waleriany.', 3),
('zolpidem',     'lawenda',          'Redukuje napięcie i lęk wieczorem.', 3),
('ranitydyna',   'lukrecja',         'DGL wspiera regenerację błony śluzowej.', 4),
('ranitydyna',   'prawoslaz',        'Tworzy ochronną warstwę śluzu.', 3),
('ranitydyna',   'siemie-lniane',    'Łagodzi zgagę i podrażnienia.', 3),
('smecta',       'czarna-jagoda',    'Garbniki działają ściągająco i przeciwbiegunkowo.', 4),
('smecta',       'pieciornik',       'Silne działanie ściągające na śluzówkę jelit.', 4),
('smecta',       'prawoslaz',        'Łagodzi podrażnienia śluzówki.', 3),
('bisakodyl',    'senes',            'Tradycyjny stymulujący środek przeczyszczający.', 4),
('bisakodyl',    'babka-jajowata',   'Łagodniejsza alternatywa — błonnik regulujący wypróżnienia.', 3),
('forlax',       'siemie-lniane',    'Łagodne działanie regulujące jelita poprzez śluzy.', 4),
('forlax',       'babka-jajowata',   'Psyllium reguluje wypróżnienia bez podrażnień.', 5),
('hepatil',      'ostropest',        'Sylimaryna chroni i regeneruje komórki wątroby.', 5),
('hepatil',      'karczoch',         'Wspiera wydzielanie żółci i trawienie tłuszczów.', 4),
('hepatil',      'mniszek',          'Wspomaga oczyszczanie wątroby.', 3),
-- Owoce i warzywa jako wsparcie leków -------------------
('ibuprofen',    'wisnie-cierpkie',  'Antocyjany działają przeciwzapalnie — porównywalnie do niskich dawek NLPZ.', 3),
('ibuprofen',    'ananas',           'Bromelina hamuje stany zapalne i obrzęki, zwłaszcza po urazach.', 3),
('paracetamol',  'wisnie-cierpkie',  'Naturalne wsparcie przeciwzapalne i lekko przeciwbólowe.', 2),
('ketoprofen',   'ananas',           'Bromelina jako naturalny enzym przeciwzapalny.', 3),
('diclofenac',   'wisnie-cierpkie',  'Antyoksydanty wiśni — wsparcie przy zapaleniach stawów.', 3),
('melatonina',   'wisnie-cierpkie',  'Naturalne źródło melatoniny — sok podnosi poziom hormonu snu.', 4),
('magne-b6',     'banan',            'Bogaty w magnez i potas — naturalna alternatywa suplementacji.', 3),
('loperamid',    'banan',            'BRAT diet — niedojrzały banan łagodzi biegunkę.', 3),
('loperamid',    'jablko',           'Pektyny wiążą wodę w jelitach — domowy sposób na biegunkę.', 4),
('loperamid',    'marchew',          'Zupa marchwiowa to klasyczny domowy sposób na biegunkę u dzieci.', 4),
('smecta',       'jablko',           'Tarte jabłko z brunatnieniem — naturalne wsparcie przy biegunce.', 3),
('smecta',       'kapusta-kiszona',  'Probiotyki odbudowują mikrobiom po biegunce.', 3),
('bisakodyl',    'suszone-sliwki',   'Sorbitol i błonnik pobudzają perystaltykę — naturalna alternatywa.', 5),
('bisakodyl',    'jablko',           'Surowe jabłko ze skórką dostarcza błonnika ułatwiającego wypróżnienia.', 3),
('forlax',       'suszone-sliwki',   'Najpopularniejszy domowy środek na zaparcia.', 5),
('forlax',       'buraki',           'Wysoka zawartość błonnika ułatwia wypróżnienia.', 3),
('forlax',       'jablko',           'Pektyny i błonnik regulują pracę jelit.', 3),
('hepatil',      'brokuly',          'Sulforafan wspomaga detoksykację wątroby na poziomie komórkowym.', 4),
('hepatil',      'kapusta-kiszona',  'Probiotyki wspierają wątrobę poprzez oś jelitowo-wątrobową.', 3),
('hepatil',      'buraki',           'Betalainy wspomagają regenerację komórek wątroby.', 3),
('espumisan',    'kapusta-kiszona',  'Probiotyki normalizują florę jelit — zmniejszają wzdęcia długoterminowo.', 3),
('drotaweryna',  'czosnek',          'Naturalne wsparcie przeciwzapalne i rozkurczowe (gotowany w mleku).', 2)
) AS r(med_slug, herb_slug, rationale, strength)
JOIN medications m ON m.slug = r.med_slug
JOIN herbs       h ON h.slug = r.herb_slug
ON CONFLICT (medication_id, herb_id) DO NOTHING;

-- Zamienniki niezdrowej żywności ------------------------
INSERT INTO food_swaps (slug, unhealthy_name_pl, unhealthy_why_pl, healthy_name_pl, healthy_why_pl, rationale_pl, icon_unhealthy, icon_healthy, sort_order) VALUES
('olej-rzepakowy-loj',
 'Oleje roślinne rafinowane (rzepakowy, słonecznikowy, sojowy)',
 'Rafinowane oleje roślinne są bogate w niestabilne kwasy omega-6 i często utleniają się podczas smażenia, generując substancje prozapalne i wolne rodniki. Proces przemysłowej rafinacji wymaga wysokich temperatur i rozpuszczalników (heksan).',
 'Łój wołowy, smalec wieprzowy, masło klarowane (ghee), oliwa z oliwek extra virgin (do zimnych dań)',
 'Tłuszcze nasycone i jednonienasycone (łój, smalec, ghee) są stabilne termicznie — nie utleniają się przy smażeniu. Tradycyjne tłuszcze zwierzęce zawierają witaminy A, D, K2, E w naturalnej formie.',
 'Smalec topiony domowo lub kupowany od lokalnego rzeźnika (300–500 g za kilka zł) wystarcza na tygodnie smażenia. Łój wołowy ma najwyższy punkt dymienia (ok. 250°C).',
 '🛢️', '🥩', 10),
('margaryna-maslo',
 'Margaryna',
 'Pierwsze margaryny zawierały tłuszcze trans (uwodornione), uznane za jedną z głównych przyczyn chorób serca. Nawet "nowsze" margaryny to mocno przetworzone produkty z dodatkami emulgatorów, barwników i aromatów.',
 'Masło prawdziwe (najlepiej od krów z trawy)',
 'Naturalny tłuszcz pełen witamin (A, D, K2), kwasu masłowego wspierającego jelita i CLA o działaniu przeciwnowotworowym. Tradycyjny produkt znany od tysięcy lat.',
 'Sprawdź skład: prawdziwe masło to wyłącznie śmietanka (ewentualnie sól). Unikać "miksów maślanych" z olejami roślinnymi.',
 '🧈', '🐄', 20),
('cukier-miod',
 'Cukier biały rafinowany',
 'Czysta sacharoza pozbawiona witamin i minerałów. Powoduje gwałtowne skoki glukozy, sprzyja insulinooporności, otyłości, próchnicy i karmi szkodliwe bakterie jelitowe.',
 'Miód naturalny, ksylitol z brzozy, syrop klonowy, daktyle (do słodzenia w przepisach)',
 'Miód zawiera enzymy, antyoksydanty i ślady mikroelementów. Ksylitol chroni zęby. Daktyle dają błonnik wraz ze słodyczą — wolniej podnoszą cukier.',
 'Wciąż używać z umiarem — nawet "naturalne" słodziki to dużo cukrów. Najlepszą opcją jest stopniowe odzwyczajanie podniebienia od słodkiego.',
 '🍬', '🍯', 30),
('syrop-glufru-daktyle',
 'Syrop glukozowo-fruktozowy (HFCS)',
 'Wysokoprzetworzony syrop kukurydziany w setkach produktów (napoje, jogurty, sosy, wędliny). Powiązany z otyłością wątroby (NAFLD), cukrzycą i chorobami serca. Bardzo szybko podnosi cukier.',
 'Świeże owoce, suszone daktyle, miód',
 'Owoce zawierają cukry razem z błonnikiem, witaminami i polifenolami — organizm trawi je wolniej. Daktyle są naturalnym, gęstym słodzidłem do wypieków i koktajli.',
 'Czytaj etykiety — HFCS kryje się w zaskakujących produktach (chleb, ketchup, wędliny).',
 '🥤', '🌴', 40),
('bialy-chleb-zytni',
 'Biały chleb pszenny',
 'Mąka rafinowana ma wysoki indeks glikemiczny i pozbawiona jest błonnika oraz witamin B z otrąb. Często zawiera dodatki polepszające teksturę (E472, glutamian).',
 'Chleb żytni na prawdziwym zakwasie',
 'Fermentacja zakwasem zmniejsza zawartość fitynianów (lepsza przyswajalność minerałów), obniża indeks glikemiczny i daje probiotyki. Żyto zawiera więcej błonnika.',
 'Kupuj w piekarniach rzemieślniczych (nie w supermarkecie z napisem "żytni" który często bazuje na drożdżach + barwniku karmelowym). Sprawdź skład: zakwas, mąka, woda, sól.',
 '🍞', '🥖', 50),
('parowki-mieso',
 'Parówki, kabanosy, mortadela (przetworzone wędliny)',
 'WHO klasyfikuje przetworzone mięso jako kancerogen grupy 1 (powiązany z rakiem jelita). Zawierają azotyny, MOM (mięso oddzielane mechanicznie), polifosforany, glutaminian sodu, dużo soli.',
 'Domowe pieczone mięso (wołowina, indyk, pierś z kurczaka), gotowana szynka od rzeźnika',
 'Niezprzetworzone mięso od dobrego producenta to białko wraz z żelazem, B12 i kreatyną. Pieczeń niedzielna starczy na kilka kanapek na tydzień.',
 'Jeśli kanapki na śniadanie — przygotuj raz w tygodniu pieczeń lub upiecz pierś. Czytaj skład: prawdziwa szynka to "mięso wieprzowe 95%, sól, przyprawy".',
 '🌭', '🥓', 60),
('platki-owsianka',
 'Słodzone płatki śniadaniowe',
 'Sam cukier z dodatkami: nawet "fitness" płatki mają 20–30% cukru. Powodują skok cukru i głód za 2 godziny. Marketing kierowany do dzieci.',
 'Owsianka z prawdziwych płatków + owoce + orzechy',
 'Pełnoziarniste płatki owsiane są tanim, szybkim i sycącym śniadaniem. Beta-glukan obniża cholesterol, błonnik wspiera trawienie.',
 'Gotuj płatki górskie/zwykłe z mlekiem lub wodą, dodaj świeże owoce, miód, orzechy. Zajmuje 5 minut, nasyca na 4 godziny.',
 '🥣', '🌾', 70),
('soki-woda-cytryna',
 'Soki owocowe z kartonu, napoje "owocowe"',
 'Soki z kartonu są pasteryzowane (utrata witamin), pozbawione błonnika i często z dodatkiem cukru. Napoje "owocowe" mają często tylko 5–10% soku.',
 'Świeży sok wyciskany, woda z cytryną, woda z owocami (infused water)',
 'Świeży sok zachowuje witaminy i enzymy, najlepiej wypić w 15 min od wyciśnięcia. Woda z cytryną wspiera trawienie i nawodnienie.',
 'Najlepiej jeść owoce w całości — błonnik spowalnia wchłanianie cukrów. Sok zostawić na okazje, codziennie pić wodę.',
 '🧃', '🍋', 80),
('sol-rafinowana-himalajska',
 'Sól warzona rafinowana (kuchenna)',
 'Czysty chlorek sodu, pozbawiony naturalnie występujących mikroelementów. Często z dodatkiem antyzbrylaczy (E535, E536). Może być kontaminowana mikroplastikiem (sól morska).',
 'Sól himalajska, sól kłodawska (z kopalni), sól szara z ewaporacji',
 'Sole nieoczyszczane zachowują śladowe minerały (magnez, wapń, potas) — kilkanaście % naturalnie. Polska sól kłodawska ma 98% NaCl + cenne dodatki.',
 'Solenie z umiarem to klucz — niezależnie od rodzaju soli, dorosły powinien spożywać do 5 g dziennie (1 łyżeczka).',
 '🧂', '⛏️', 90),
('mleko-uht-swieze',
 'Mleko UHT (długoterminowe)',
 'Wysokotemperaturowa pasteryzacja (140°C, 4 sek.) niszczy część witamin (B1, B12, C) i naturalne enzymy. Białka denaturują, co u części osób powoduje gorszą tolerancję.',
 'Mleko świeże od krowy (pasteryzowane krótko), mleko od lokalnego rolnika',
 'Mleko świeże ma więcej witamin, enzymów i naturalnych probiotyków. Mleko od krów z trawy zawiera 2–5 razy więcej omega-3 i CLA.',
 'Sprawdź lokalne gospodarstwa, mleko prosto od rolnika (po prawidłowym zagotowaniu). Mleko surowe można też kupić w mlekomatach w wielu miastach.',
 '📦', '🥛', 100),
('jogurt-slodzony-naturalny',
 'Jogurty owocowe słodzone',
 'Mała ilość owoców i bardzo dużo cukru (10–15 g/100 g). Często mleko w proszku zamiast pełnowartościowego, syrop glukozowo-fruktozowy, barwniki, aromaty.',
 'Jogurt naturalny bez cukru + świeże owoce + miód lub orzechy',
 'Jogurt naturalny dostarcza białka i probiotyków bez zbędnych dodatków. Sam decydujesz o słodyczy i konsystencji.',
 'Najlepiej grecki lub bałkański — mają więcej białka. Jeszcze lepiej kefir lub maślanka — bogatsze w probiotyki.',
 '🍓', '🥄', 110),
('ser-topiony-naturalny',
 'Ser topiony w plasterkach',
 'Mieszanka serowa z fosforanami, emulgatorami, solą, barwnikami. "Ser" to często mniejszość składu. Dużo soli (1500 mg/100 g).',
 'Prawdziwy ser żółty dojrzewający, ser kozi, twaróg',
 'Tradycyjny ser dojrzewający (gouda, ementaler, oscypek) to skoncentrowane białko, wapń, witaminy K2. Sery kozie są lepiej tolerowane.',
 'Czytaj skład: pierwsze "mleko" lub "ser" oznacza prawdziwy produkt. Topione i "produkty seropodobne" zawsze pomijać.',
 '🟨', '🧀', 120)
ON CONFLICT (slug) DO UPDATE SET
  unhealthy_name_pl = EXCLUDED.unhealthy_name_pl,
  unhealthy_why_pl  = EXCLUDED.unhealthy_why_pl,
  healthy_name_pl   = EXCLUDED.healthy_name_pl,
  healthy_why_pl    = EXCLUDED.healthy_why_pl,
  rationale_pl      = EXCLUDED.rationale_pl,
  icon_unhealthy    = EXCLUDED.icon_unhealthy,
  icon_healthy      = EXCLUDED.icon_healthy,
  sort_order        = EXCLUDED.sort_order;
