-- =====================================================
-- ZielonaApteka — dane startowe
-- Wykonaj w SQL Editor po seed/schema.sql.
-- Bezpieczne do wielokrotnego uruchamiania (ON CONFLICT DO NOTHING).
-- =====================================================

-- Kategorie ---------------------------------------------
INSERT INTO categories (slug, name_pl, description, icon, sort_order) VALUES
('bol',       'Ból',                'Leki i zioła stosowane przy bólu głowy, mięśni i stanach zapalnych.', '🤕', 10),
('sen',       'Sen i uspokojenie',  'Wsparcie zdrowego snu, redukcja stresu i napięcia nerwowego.',         '🌙', 20),
('trawienie', 'Trawienie',          'Niestrawność, wzdęcia, biegunka, zgaga i inne dolegliwości żołądka.',  '🌿', 30)
ON CONFLICT (slug) DO NOTHING;

-- Zioła -------------------------------------------------
-- (Pierwsze 15 ziół + 7 nowych dodanych pod koniec.)
INSERT INTO herbs (slug, name_pl, latin_name, description_pl, how_to_use_pl, cautions_pl) VALUES
('wierzba-biala',    'Wierzba biała',     'Salix alba',
 'Kora wierzby zawiera salicynę — naturalny prekursor kwasu salicylowego, działa przeciwbólowo, przeciwgorączkowo i przeciwzapalnie.',
 'Najczęściej w postaci naparu z kory (1 łyżeczka na szklankę wrzątku, 10–15 min) lub gotowych ekstraktów w tabletkach.',
 'Nie stosować przy alergii na salicylany, w ciąży, u dzieci poniżej 12 r.ż. oraz przy chorobach krzepnięcia krwi.'),
('wiazowka-blotna',  'Wiązówka błotna',   'Filipendula ulmaria',
 'Zawiera salicylany i flawonoidy — działa przeciwzapalnie, przeciwbólowo i przeciwgorączkowo, wspiera stawy.',
 'Napar z kwiatów: 1–2 łyżeczki na szklankę wrzątku, 2–3 razy dziennie.',
 'Przeciwwskazania jak przy wierzbie — alergia na salicylany, astma, ciąża.'),
('imbir',            'Imbir',             'Zingiber officinale',
 'Działa przeciwzapalnie, przeciwbólowo i przeciwwymiotnie. Pomaga przy bólach mięśni i miesiączkowych.',
 'Świeży korzeń (plasterki) zalany wrzątkiem, gotowe herbaty lub kapsułki.',
 'Ostrożnie przy lekach przeciwzakrzepowych i kamicy żółciowej.'),
('melisa-lekarska',  'Melisa lekarska',   'Melissa officinalis',
 'Łagodne działanie uspokajające, nasenne i rozkurczowe. Ułatwia zasypianie i redukuje stres.',
 'Napar z liści: 1–2 łyżeczki na szklankę wrzątku, wieczorem.',
 'Możliwe interakcje z lekami uspokajającymi i przeciwtarczycowymi.'),
('kozlek-lekarski',  'Kozłek lekarski (waleriana)', 'Valeriana officinalis',
 'Klasyczne zioło na bezsenność i niepokój. Działa wyciszająco bez efektu otępiającego rano.',
 'Napar z korzenia, krople lub tabletki — przyjmować 30–60 min przed snem.',
 'Nie łączyć z alkoholem i benzodiazepinami; ostrożnie przy prowadzeniu pojazdów.'),
('chmiel-zwyczajny', 'Chmiel zwyczajny',  'Humulus lupulus',
 'Szyszki chmielu działają uspokajająco i nasennie. Często łączone z walerianą i melisą.',
 'Napar z szyszek lub gotowe preparaty złożone.',
 'Nie zaleca się przy depresji oraz w ciąży.'),
('lawenda',          'Lawenda',           'Lavandula angustifolia',
 'Olejek i kwiaty lawendy redukują napięcie, lęk i poprawiają jakość snu.',
 'Napar z kwiatów, olejek do aromaterapii, kapsułki ze standaryzowanym ekstraktem.',
 'Olejek wyłącznie do użytku zewnętrznego lub wziewnego (poza preparatami doustnymi).'),
('czarna-jagoda',    'Czarna jagoda (borówka czernica)', 'Vaccinium myrtillus',
 'Suszone owoce mają działanie ściągające i przeciwbiegunkowe dzięki garbnikom.',
 'Odwar z suszonych owoców (1 łyżka na szklankę, gotować 10 min), 2–3 razy dziennie.',
 'Nie stosować dłużej niż kilka dni; uwaga na zaparcia przy przedawkowaniu.'),
('pieciornik',       'Pięciornik kurze ziele', 'Potentilla erecta',
 'Bogaty w garbniki — działa silnie ściągająco, przeciwbiegunkowo i przeciwzapalnie na śluzówki.',
 'Odwar z kłącza: 1 łyżeczka na szklankę, gotować 5 min.',
 'Krótkotrwale; przy wrażliwym żołądku może powodować mdłości.'),
('koper-wloski',     'Koper włoski',      'Foeniculum vulgare',
 'Owoce kopru działają wiatropędnie i rozkurczowo — łagodzą wzdęcia i kolki.',
 'Napar z rozgniecionych owoców: 1 łyżeczka na szklankę wrzątku, po posiłkach.',
 'Generalnie bezpieczny; ostrożnie przy alergii na rośliny baldaszkowate.'),
('mieta-pieprzowa',  'Mięta pieprzowa',   'Mentha × piperita',
 'Olejek mentolowy działa rozkurczowo na mięśnie gładkie przewodu pokarmowego.',
 'Napar z liści po posiłkach lub kapsułki dojelitowe z olejkiem (IBS).',
 'Nasila refluks żołądkowo-przełykowy; nie stosować u niemowląt.'),
('rumianek',         'Rumianek',          'Matricaria chamomilla',
 'Działa przeciwzapalnie, rozkurczowo i wiatropędnie. Łagodzi podrażnienia żołądka.',
 'Napar z koszyczków kwiatowych: 1 łyżka na szklankę wrzątku.',
 'Rzadkie alergie krzyżowe (ambrozja).'),
('lukrecja',         'Lukrecja',          'Glycyrrhiza glabra',
 'Korzeń lukrecji wspomaga regenerację błony śluzowej żołądka, łagodzi zgagę.',
 'Odwar z korzenia lub gotowe ekstrakty DGL (deglicyrrhized).',
 'Długotrwałe stosowanie podnosi ciśnienie krwi i obniża potas. Nie w nadciśnieniu i ciąży.'),
('siemie-lniane',    'Siemię lniane',     'Linum usitatissimum',
 'Śluzy roślinne pokrywają śluzówkę żołądka i przełyku — łagodzą zgagę i podrażnienia.',
 'Macerat: 1 łyżka nasion zalana letnią wodą na 20–30 min, pić ze śluzem.',
 'Świeżo zmielone siemię — krótkotrwałe przechowywanie.'),
('prawoslaz',        'Prawoślaz lekarski','Althaea officinalis',
 'Korzeń prawoślazu zawiera śluzy łagodzące podrażnienia gardła, przełyku i żołądka.',
 'Macerat na zimno z korzenia (1 łyżka na szklankę, 1–2 godz.).',
 'Może opóźniać wchłanianie innych leków — odstęp 1–2 godz.'),
('harpagofyt',       'Czarci pazur (harpagofyt)', 'Harpagophytum procumbens',
 'Korzeń pochodzący z Afryki o silnym działaniu przeciwbólowym i przeciwzapalnym, szczególnie w bólach stawów i kręgosłupa.',
 'Standaryzowane kapsułki 400–600 mg dziennie; napar z korzenia gorzki.',
 'Choroba wrzodowa, kamica żółciowa, ciąża; może obniżać poziom cukru.'),
('dziurawiec',       'Dziurawiec zwyczajny', 'Hypericum perforatum',
 'Tradycyjnie stosowany przy łagodnych stanach depresyjnych, niepokoju i bezsenności.',
 'Napar z ziela: 1 łyżeczka na szklankę, 2 razy dziennie.',
 'Bardzo dużo interakcji lekowych (leki antykoncepcyjne, przeciwzakrzepowe, antydepresanty)! Fotouczulający.'),
('owies',            'Owies zwyczajny', 'Avena sativa',
 'Niedojrzałe ziarno owsa działa odżywczo na układ nerwowy, łagodzi napięcie i wspomaga sen.',
 'Owsianka, napar ze słomy owsianej, gotowe nalewki.',
 'Bezpieczny; uwaga przy celiakii (zanieczyszczenia glutenem).'),
('senes',            'Senes (strączyniec)', 'Senna alexandrina',
 'Liście i strąki działają silnie przeczyszczająco poprzez pobudzenie perystaltyki jelita grubego.',
 'Napar lub gotowe tabletki, krótkotrwale (do 1–2 tygodni).',
 'Nie przewlekle (przyzwyczajenie jelit), nie w ciąży i u dzieci, kolki, biegunka.'),
('babka-jajowata',   'Babka jajowata (psyllium)', 'Plantago ovata',
 'Łuski nasion (psyllium) tworzą żel wodny — błonnik regulujący wypróżnienia, działa zarówno przy zaparciach jak i biegunkach.',
 'Łyżeczka łusek wymieszana z dużą szklanką wody, dziennie.',
 'Pij dużo wody; może opóźniać wchłanianie leków — odstęp 2 godz.'),
('ostropest',        'Ostropest plamisty', 'Silybum marianum',
 'Sylimaryna chroni komórki wątroby i wspiera ich regenerację.',
 'Mielone nasiona (1 łyżka dziennie) lub kapsułki ze standaryzowanym ekstraktem.',
 'Ogólnie bezpieczny; możliwa alergia u osób uczulonych na rośliny astrowate.'),
('karczoch',         'Karczoch zwyczajny', 'Cynara scolymus',
 'Liście karczocha pobudzają wydzielanie żółci i wspierają trawienie tłuszczów.',
 'Kapsułki z ekstraktem lub napar z liści.',
 'Niedrożność dróg żółciowych, kamica; alergie na astrowate.'),
('mniszek',          'Mniszek lekarski', 'Taraxacum officinale',
 'Korzeń wspiera wątrobę i nerki, działa moczopędnie.',
 'Napar z korzenia lub liści, kawa z korzenia mniszka.',
 'Niedrożność dróg żółciowych, ostre stany żołądka.')
ON CONFLICT (slug) DO NOTHING;

-- Leki --------------------------------------------------
INSERT INTO medications (slug, name_pl, active_substance, brand_examples, purpose_pl, description_pl, side_effects_pl, category_id)
SELECT * FROM (VALUES
('ibuprofen',    'Ibuprofen',    'Ibuprofen',                'Ibuprom, Nurofen, MIG',
 'Ból, gorączka, stany zapalne',
 'Niesteroidowy lek przeciwzapalny (NLPZ) o działaniu przeciwbólowym, przeciwzapalnym i przeciwgorączkowym. Stosowany w bólu głowy, mięśni, miesiączkowym i przy infekcjach.',
 'Podrażnienie żołądka, nudności, ryzyko krwawień z przewodu pokarmowego, wzrost ciśnienia.',
 (SELECT id FROM categories WHERE slug='bol')),
('paracetamol',  'Paracetamol',  'Paracetamol',              'Apap, Panadol, Codipar',
 'Ból, gorączka',
 'Łagodny lek przeciwbólowy i przeciwgorączkowy. Nie ma działania przeciwzapalnego, ale jest dobrze tolerowany przez żołądek.',
 'Przy przedawkowaniu — toksyczne uszkodzenie wątroby. Ostrożnie z alkoholem.',
 (SELECT id FROM categories WHERE slug='bol')),
('aspiryna',     'Aspiryna',     'Kwas acetylosalicylowy',   'Polopiryna, Aspirin',
 'Ból, gorączka, profilaktyka sercowo-naczyniowa',
 'Klasyczny NLPZ. W małych dawkach stosowany jako lek przeciwzakrzepowy. W większych — przeciwbólowo i przeciwzapalnie.',
 'Krwawienia z przewodu pokarmowego, alergie, zespół Reye u dzieci.',
 (SELECT id FROM categories WHERE slug='bol')),
('melatonina',   'Melatonina',   'Melatonina',               'Melatonina LEK-AM, Circadin',
 'Trudności z zasypianiem, jet lag',
 'Hormon wytwarzany przez szyszynkę regulujący rytm dobowy. Stosowany przy bezsenności i zmianach stref czasowych.',
 'Senność rano, bóle głowy, żywe sny. Może wchodzić w interakcje z lekami przeciwzakrzepowymi.',
 (SELECT id FROM categories WHERE slug='sen')),
('hydroksyzyna', 'Hydroksyzyna', 'Hydroksyzyna',             'Atarax, Hydroxyzinum VP',
 'Lęk, niepokój, bezsenność',
 'Lek przeciwhistaminowy o działaniu uspokajającym i przeciwlękowym. Wymaga recepty.',
 'Senność, suchość w ustach, zaburzenia rytmu serca (długie QT). Nie łączyć z alkoholem.',
 (SELECT id FROM categories WHERE slug='sen')),
('loperamid',    'Loperamid',    'Loperamid',                'Stoperan, Imodium, Laremid',
 'Biegunka',
 'Hamuje perystaltykę jelit, wskazany w ostrej, niezakaźnej biegunce u dorosłych.',
 'Zaparcia, bóle brzucha. Niewskazany w biegunce z gorączką lub krwią w stolcu.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('espumisan',    'Espumisan',    'Symetykon',                'Espumisan, Esputicon',
 'Wzdęcia, gazy',
 'Środek przeciwpieniący — rozbija pęcherzyki gazu w jelitach. Nie wchłania się do krwiobiegu.',
 'Praktycznie brak; rzadko reakcje alergiczne.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('omeprazol',    'Omeprazol',    'Omeprazol',                'Polprazol, Helicid, Bioprazol',
 'Zgaga, refluks, choroba wrzodowa',
 'Inhibitor pompy protonowej — zmniejsza wydzielanie kwasu solnego w żołądku.',
 'Bóle głowy, biegunka, długotrwale — niedobór B12 i magnezu, ryzyko złamań.',
 (SELECT id FROM categories WHERE slug='trawienie')),
-- Nowe leki ----------------------------------------------
('ketoprofen',   'Ketoprofen',   'Ketoprofen',               'Ketonal, Bi-Profenid, Profenid',
 'Ból, stany zapalne stawów',
 'Niesteroidowy lek przeciwzapalny (NLPZ) — silnie przeciwbólowy i przeciwzapalny, używany w bólach stawów, mięśni i pooperacyjnych.',
 'Podrażnienie żołądka, owrzodzenia, problemy nerkowe, fotoalergia (żel).',
 (SELECT id FROM categories WHERE slug='bol')),
('diclofenac',   'Diclofenac',   'Diklofenak',               'Voltaren, Olfen, Naklofen, Dicloratio',
 'Ból, zapalenie stawów',
 'NLPZ stosowany w bólu kostno-stawowym, urazach, dnie moczanowej. Dostępny doustnie i miejscowo (żel).',
 'Powikłania sercowo-naczyniowe przy długim stosowaniu, podrażnienie żołądka.',
 (SELECT id FROM categories WHERE slug='bol')),
('naproksen',    'Naproksen',    'Naproksen',                'Naproxen, Aleve, Naprosyn',
 'Ból, gorączka, zapalenie',
 'NLPZ o długim działaniu (do 12 godzin). Często stosowany w bólach miesiączkowych i głowy.',
 'Podrażnienie żołądka, retencja płynów, ostrożnie u osób z chorobami serca.',
 (SELECT id FROM categories WHERE slug='bol')),
('drotaweryna',  'No-Spa',       'Drotaweryna',              'No-Spa, Galospa, Drotaverin',
 'Bóle skurczowe (kolka, miesiączkowy)',
 'Lek rozkurczowy działający na mięśnie gładkie — kolka jelitowa, żółciowa, nerkowa, ból miesiączkowy.',
 'Spadki ciśnienia, zawroty głowy. Nie u dzieci poniżej 1 r.ż.',
 (SELECT id FROM categories WHERE slug='bol')),
('doksylamina',  'Doksylamina',  'Doksylamina',              'Noctis, Donormyl',
 'Krótkotrwała bezsenność',
 'Lek przeciwhistaminowy I generacji o silnym działaniu nasennym. Bez recepty.',
 'Senność rano, suchość w ustach, zaparcia. Tolerancja przy częstym użyciu.',
 (SELECT id FROM categories WHERE slug='sen')),
('magne-b6',     'Magne B6',     'Magnez + witamina B6',     'Magne B6, Magnefar B6, Slow Mag',
 'Niedobór magnezu, napięcie nerwowe, sen',
 'Suplementacja magnezu z B6 wspiera układ nerwowy, łagodzi skurcze i ułatwia zasypianie.',
 'Biegunka przy dużych dawkach, ostrożnie przy chorobach nerek.',
 (SELECT id FROM categories WHERE slug='sen')),
('zolpidem',     'Stilnox (Zolpidem)', 'Zolpidem',           'Stilnox, Hypnogen, Nasen',
 'Ciężka bezsenność (na receptę)',
 'Niebenzodiazepinowy lek nasenny o szybkim działaniu. Stosowany krótkotrwale (do 4 tygodni).',
 'Uzależnienie, ataksja, halucynacje, lunatykowanie. Nie z alkoholem.',
 (SELECT id FROM categories WHERE slug='sen')),
('ranitydyna',   'Ranigast',     'Ranitydyna / Famotydyna',  'Ranigast, Pepcid, Famogast',
 'Zgaga, nadkwaśność',
 'Bloker receptora H2 — zmniejsza wydzielanie kwasu żołądkowego, łagodniejszy od IPP.',
 'Bóle głowy, biegunka. Ranitydyna wycofana w wielu krajach (zanieczyszczenia NDMA).',
 (SELECT id FROM categories WHERE slug='trawienie')),
('smecta',       'Smecta',       'Diosmektyt',               'Smecta, Smectago',
 'Ostra biegunka',
 'Krzemian glinu o właściwościach absorpcyjnych — wiąże toksyny i drobnoustroje, łagodzi biegunkę.',
 'Zaparcia. Może opóźniać wchłanianie innych leków — odstęp 2 godz.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('bisakodyl',    'Dulcolax (Bisakodyl)', 'Bisakodyl',        'Dulcolax, Bisacodyl',
 'Zaparcia',
 'Stymulujący środek przeczyszczający — pobudza perystaltykę jelita grubego po 6–12 godzinach.',
 'Skurcze brzucha, biegunka, utrata elektrolitów. Nie do długotrwałego użycia.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('forlax',       'Forlax (Makrogol)', 'Makrogol 4000',       'Forlax, Movicol, Fortrans',
 'Zaparcia',
 'Osmotyczny środek przeczyszczający — wiąże wodę w jelicie. Łagodny, nadaje się do długiego stosowania.',
 'Wzdęcia, lekkie odwodnienie. Bezpieczny u dzieci i kobiet w ciąży.',
 (SELECT id FROM categories WHERE slug='trawienie')),
('hepatil',      'Hepatil',      'Asparaginian L-ornityny',  'Hepatil, Hepatil Trawienie',
 'Wsparcie wątroby',
 'Aminokwas wspomagający detoksykację amoniaku w wątrobie. Stosowany przy stanach zapalnych i niewydolności.',
 'Generalnie bezpieczny; ostrożnie przy ciężkiej niewydolności nerek.',
 (SELECT id FROM categories WHERE slug='trawienie'))
) AS v(slug, name_pl, active_substance, brand_examples, purpose_pl, description_pl, side_effects_pl, category_id)
ON CONFLICT (slug) DO NOTHING;

-- Powiązania lek <-> zioło ------------------------------
INSERT INTO medication_herbs (medication_id, herb_id, rationale_pl, strength)
SELECT m.id, h.id, r.rationale, r.strength
FROM (VALUES
('ibuprofen',    'wierzba-biala',    'Naturalny salicylan o działaniu przeciwbólowym i przeciwzapalnym — botaniczny pierwowzór aspiryny.', 4),
('ibuprofen',    'wiazowka-blotna',  'Bogata w salicylany — wspiera stawy i działa przeciwzapalnie.', 3),
('paracetamol',  'wierzba-biala',    'Łagodny efekt przeciwbólowy i przeciwgorączkowy.', 3),
('paracetamol',  'imbir',            'Działa przeciwbólowo i przeciwzapalnie, szczególnie w bólach mięśni i miesiączkowych.', 3),
('aspiryna',     'wierzba-biala',    'Bezpośredni botaniczny odpowiednik — kora wierzby była pierwowzorem aspiryny.', 5),
('aspiryna',     'wiazowka-blotna',  'Druga klasyczna roślina salicylanowa.', 4),
('melatonina',   'melisa-lekarska',  'Łagodzi zasypianie i redukuje napięcie wieczorem.', 3),
('melatonina',   'kozlek-lekarski',  'Skraca czas zasypiania i poprawia jakość snu.', 4),
('hydroksyzyna', 'melisa-lekarska',  'Działa przeciwlękowo i uspokajająco.', 3),
('hydroksyzyna', 'chmiel-zwyczajny', 'Wzmacnia działanie waleriany i melisy.', 3),
('hydroksyzyna', 'lawenda',          'Redukuje lęk, poprawia jakość snu.', 4),
('loperamid',    'czarna-jagoda',    'Garbniki działają ściągająco i przeciwbiegunkowo.', 4),
('loperamid',    'pieciornik',       'Silne działanie ściągające na śluzówkę jelit.', 4),
('espumisan',    'koper-wloski',     'Wiatropędnie usuwa nadmiar gazów i łagodzi kolki.', 4),
('espumisan',    'mieta-pieprzowa',  'Rozkurcza mięśnie gładkie jelit.', 4),
('espumisan',    'rumianek',         'Łagodzi podrażnienia i wspiera trawienie.', 3),
('omeprazol',    'lukrecja',         'Wspiera regenerację błony śluzowej żołądka — szczególnie postać DGL.', 4),
('omeprazol',    'siemie-lniane',    'Śluzy chronią przełyk i żołądek przed kwasem.', 3),
('omeprazol',    'prawoslaz',        'Tworzy ochronną warstwę śluzu na śluzówce.', 3),
-- Nowe leki -> zioła ------------------------------------
('ketoprofen',   'wierzba-biala',    'Salicylany działają przeciwzapalnie i przeciwbólowo.', 4),
('ketoprofen',   'harpagofyt',       'Czarci pazur — silne wsparcie przy bólach stawów i kręgosłupa.', 5),
('ketoprofen',   'imbir',            'Działa przeciwzapalnie i przeciwbólowo na stawy.', 3),
('diclofenac',   'wierzba-biala',    'Naturalny salicylan o działaniu przeciwzapalnym.', 4),
('diclofenac',   'harpagofyt',       'Tradycyjne wsparcie przy zapaleniach stawów.', 4),
('diclofenac',   'wiazowka-blotna',  'Salicylany roślinne łagodzące stany zapalne.', 3),
('naproksen',    'wierzba-biala',    'Klasyczny botaniczny prekursor NLPZ.', 4),
('naproksen',    'wiazowka-blotna',  'Wspiera leczenie bólów reumatycznych.', 3),
('drotaweryna',  'mieta-pieprzowa',  'Olejek mentolowy rozkurcza mięśnie gładkie jelit.', 4),
('drotaweryna',  'koper-wloski',     'Działa rozkurczowo i wiatropędnie.', 3),
('drotaweryna',  'melisa-lekarska',  'Łagodne działanie rozkurczowe i uspokajające.', 3),
('doksylamina',  'kozlek-lekarski',  'Tradycyjne zioło na sen.', 4),
('doksylamina',  'melisa-lekarska',  'Łagodzi zasypianie.', 3),
('doksylamina',  'chmiel-zwyczajny', 'Działa nasennie, wzmacnia walerianę.', 3),
('magne-b6',     'owies',            'Niedojrzałe ziarno owsa odżywia układ nerwowy.', 3),
('magne-b6',     'melisa-lekarska',  'Łagodzi napięcie nerwowe.', 3),
('zolpidem',     'kozlek-lekarski',  'Najsilniejsze tradycyjne zioło na bezsenność.', 4),
('zolpidem',     'chmiel-zwyczajny', 'Wzmacnia działanie waleriany.', 3),
('zolpidem',     'lawenda',          'Redukuje napięcie i lęk wieczorem.', 3),
('ranitydyna',   'lukrecja',         'DGL wspiera regenerację błony śluzowej.', 4),
('ranitydyna',   'prawoslaz',        'Tworzy ochronną warstwę śluzu.', 3),
('ranitydyna',   'siemie-lniane',    'Łagodzi zgagę i podrażnienia.', 3),
('smecta',       'czarna-jagoda',    'Garbniki działają ściągająco i przeciwbiegunkowo.', 4),
('smecta',       'pieciornik',       'Silne działanie ściągające na śluzówkę jelit.', 4),
('smecta',       'prawoslaz',        'Łagodzi podrażnienia śluzówki.', 3),
('bisakodyl',    'senes',            'Tradycyjny stymulujący środek przeczyszczający.', 4),
('bisakodyl',    'babka-jajowata',   'Łagodniejsza alternatywa — błonnik regulujący wypróżnienia.', 3),
('forlax',       'siemie-lniane',    'Łagodne działanie regulujące jelita poprzez śluzy.', 4),
('forlax',       'babka-jajowata',   'Psyllium reguluje wypróżnienia bez podrażnień.', 5),
('hepatil',      'ostropest',        'Sylimaryna chroni i regeneruje komórki wątroby.', 5),
('hepatil',      'karczoch',         'Wspiera wydzielanie żółci i trawienie tłuszczów.', 4),
('hepatil',      'mniszek',          'Wspomaga oczyszczanie wątroby.', 3)
) AS r(med_slug, herb_slug, rationale, strength)
JOIN medications m ON m.slug = r.med_slug
JOIN herbs       h ON h.slug = r.herb_slug
ON CONFLICT (medication_id, herb_id) DO NOTHING;
